### ISSUE TITLE
Missing text color (w/b) for each background fill color.

### ISSUE THREAD

**Issue by hakunin** [shuhei/material-colors#5]
Hi,
one important piece thats missing here are the foreground colors (at least not present in the JSON file).

**Comment by shuhei** [comment]
Which one in [the Material Design website](https://www.google.com/design/spec/style/color.html) do you mean?

**Comment by hakunin** [comment]
Sure, if you look at the pallete, the colors have each either black or white text and this is different throughout the color scheme (blue's white text starts at 500, while indigo uses white from 300).
https://www.dropbox.com/s/dtk89mroi5z4maz/Screenshot%202016-02-18%2010.03.25.png?dl=0

**Comment by shuhei** [comment]
Got it! So they are either black or white of alpha 0.87. I'll think about how to encode the information to json, js and css variants. Thanks!

**Comment by shuhei** [comment]
I assume that this was fixed by #8. Please reopen it if it's not.
