### ISSUE TITLE
Can't Import Sass Files

### ISSUE THREAD

**Issue by ccravens** [shuhei/material-colors#7]
I used bower to install the material-colors dependency. The dist/ folder contains a file with .scss and .sass. When attempting to use sass to import the file like so:

```sass
@import '../../bower_components/material-colors/dist/colors.scss';
```

I get the following error:
```bash
Error: It's not clear which file to import for '@import "../../bower_components/material-colors/dist/colors"'.
       Candidates:
         ../../bower_components/material-colors/dist/colors.scss
         ../../bower_components/material-colors/dist/colors.sass
         ../../bower_components/material-colors/dist/colors.css
       Please delete or rename all but one of these files.
```

Can we not rename or move these files so we can import them appropriately with SASS?

**Comment by shuhei** [comment]
I don't think this is an issue of this module but the tool that threw the error. What tool do you use? You can contact the maintainers of it about this problem.
